<?php 
    echo "Bangun Ruang<br>";
    echo "=====================<br>";
    $v = "Kubus";
    $rumus = "<br> Volume = Rusuk**3 ";
    $contoh = "Misal panjang Rusuk = 6 Maka, Volume kubus?";   
    echo "Volume $v <br>";
    echo "Rumus $rumus <br>" ;
    echo " $contoh <br>";
    $r = 6;
    $v = $r **3 ;
    echo "$r **3 = $v <br>";
    echo "=====================<br>";
    $v = "Balok";
    $rumus = "<br> Volume = Panjang * Lebar * Tinggi ";
    $contoh = "Misal panjang  = 14 Lebar = 6 dan Tinggi 8 Maka, Volume Balok?";   
    echo "Volume $v <br>";
    echo "Rumus $rumus <br>" ;
    echo " $contoh <br>";
    $p = 14;
    $l = 6;
    $t = 8;
    $v = $p * $l * $t ;
    echo " $p * $l * $t = $v <br>";
    echo "=====================<br>";
    $v = "Limas segiempat";
    $rumus = "<br> Volume = 1/3 * Luas Alas * Tinggi ";
    $contoh = "Misal Luas Alas  = 48 Tinggi 10 Maka, Volume Limas segiempat?";   
    echo "Volume $v <br>";
    echo "Rumus $rumus <br>" ;
    echo " $contoh <br>";
    $la= 48;
    $t = 10;
    $v = 1/3 * $la * $t ;
    echo " 1/3 * $la * $t = $v <br>";
    echo "=====================<br>";
    ?>